"""Pin the agent context manifest (docs/agent/index.yml) to its structural contract.

Checks:
- The index file exists and parses as valid YAML.
- Every subsystem has the required fields.
- Every path referenced in folio, binding_docs, reference_docs, and source_roots
  exists on disk — so index drift is caught in CI rather than discovered mid-session.
- Every generated context pack exists and carries the NOT-SOURCE-OF-TRUTH marker
  (generated by tools/agent_context/build_pack.py; should be committed).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import pytest
import yaml

_REPO_ROOT = Path(__file__).resolve().parents[3]
_INDEX_PATH = _REPO_ROOT / "docs" / "agent" / "index.yml"
_GENERATED_DIR = _REPO_ROOT / "docs" / "agent" / "generated"
_NOT_SOURCE_MARKER = "NOT SOURCE OF TRUTH"
_REQUIRED_FIELDS = (
    "folio",
    "binding_docs",
    "source_roots",
    "do_not_create",
    "verification",
)


def _load_index() -> dict[str, Any]:
    with _INDEX_PATH.open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


@pytest.fixture(scope="module")
def index_data() -> dict[str, Any]:
    assert _INDEX_PATH.exists(), f"Agent context index not found: {_INDEX_PATH}"
    data = _load_index()
    assert isinstance(data, dict), "index.yml must be a YAML mapping"
    assert "subsystems" in data, "index.yml must have a 'subsystems' key"
    return data


@pytest.fixture(scope="module")
def subsystems(index_data: dict[str, Any]) -> dict[str, Any]:
    return index_data["subsystems"]


def test_index_file_exists() -> None:
    assert _INDEX_PATH.exists(), f"docs/agent/index.yml not found at {_INDEX_PATH}"


def test_index_has_at_least_one_subsystem(subsystems: dict[str, Any]) -> None:
    assert subsystems, "index.yml subsystems block must not be empty"


@pytest.mark.parametrize("field", _REQUIRED_FIELDS)
def test_all_subsystems_have_required_field(
    subsystems: dict[str, Any], field: str
) -> None:
    missing = [name for name, sub in subsystems.items() if not sub.get(field)]
    assert (
        not missing
    ), f"These subsystems are missing or have empty '{field}': {missing}"


def test_all_folio_paths_exist(subsystems: dict[str, Any]) -> None:
    missing = []
    for name, sub in subsystems.items():
        folio = sub.get("folio", "")
        if folio and not (_REPO_ROOT / folio).exists():
            missing.append(f"{name}: {folio}")
    assert not missing, f"Folio paths not found on disk:\n" + "\n".join(missing)


def test_all_binding_doc_paths_exist(subsystems: dict[str, Any]) -> None:
    missing = []
    for name, sub in subsystems.items():
        for doc in sub.get("binding_docs", []):
            if not (_REPO_ROOT / doc).exists():
                missing.append(f"{name}: {doc}")
    assert not missing, "binding_docs paths not found:\n" + "\n".join(missing)


def test_all_reference_doc_paths_exist(subsystems: dict[str, Any]) -> None:
    missing = []
    for name, sub in subsystems.items():
        for doc in sub.get("reference_docs", []):
            if not (_REPO_ROOT / doc).exists():
                missing.append(f"{name}: {doc}")
    assert not missing, "reference_docs paths not found:\n" + "\n".join(missing)


def test_all_source_root_paths_exist(subsystems: dict[str, Any]) -> None:
    missing = []
    for name, sub in subsystems.items():
        for root in sub.get("source_roots", []):
            if not (_REPO_ROOT / root).exists():
                missing.append(f"{name}: {root}")
    assert (
        not missing
    ), "source_roots paths not found on disk (file or directory):\n" + "\n".join(
        missing
    )


def test_generated_packs_exist(subsystems: dict[str, Any]) -> None:
    missing = []
    for name in subsystems:
        pack = _GENERATED_DIR / f"{name}.context.md"
        if not pack.exists():
            missing.append(str(pack.relative_to(_REPO_ROOT)))
    assert not missing, (
        "Generated context packs are missing. "
        "Run `python3.10 tools/agent_context/build_pack.py` and commit the output.\n"
        + "\n".join(missing)
    )


def test_generated_packs_carry_not_source_marker(subsystems: dict[str, Any]) -> None:
    bad = []
    for name in subsystems:
        pack = _GENERATED_DIR / f"{name}.context.md"
        if pack.exists() and _NOT_SOURCE_MARKER not in pack.read_text(encoding="utf-8"):
            bad.append(str(pack.relative_to(_REPO_ROOT)))
    assert not bad, (
        f"These generated packs are missing the '{_NOT_SOURCE_MARKER}' marker:\n"
        + "\n".join(bad)
    )
