"""AgentContextPack generator — index-or-manifest input (Lane B8, spec 2.10).

Generates per-area *context packs* — the curated "what an agent must know to
work in this area" bundles — from a project index. Two input forms are
accepted (design-spec 2.10: the generator meets hosts where they are):

  1. the kit's own ``project.index.json`` (``{"areas": [...]}``, planted by
     the adopt flow as a skeleton), and
  2. a manifest snapshot (``{"subsystems": [...]}``) as produced by a host's
     existing subsystem manifest — mapped onto the same area shape with
     sensible fallbacks.

Each pack is written under ``<state_dir>/contextpacks/`` and opens with the
``NOT SOURCE OF TRUTH`` marker: packs are build artifacts — regenerate them
from the index, never hand-edit them. Pure stdlib; every write goes through
``atomic_write_text``.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from engine.lib.atomicio import atomic_write_text
from engine.lib.config import Config

_PACK_MARKER = (
    "<!-- NOT SOURCE OF TRUTH — generated by substrate-kit; "
    "regenerate, do not edit. -->"
)

# The list-valued fields of the canonical area shape, in emit order.
_PACK_LIST_KEYS = (
    "binding_docs",
    "source_roots",
    "do_not_create",
    "gates",
    "verification",
)

_PACK_SECTION_TITLES = {
    "binding_docs": "Binding docs",
    "source_roots": "Source roots",
    "do_not_create": "Do-not-create",
    "gates": "Gates",
    "verification": "Verification",
}

_PACK_SLUG_STRIP_RE = re.compile(r"[^a-z0-9._-]")
_PACK_SLUG_SEP_RE = re.compile(r"[\s/\\]+")


def _pack_slug(name: str) -> str:
    """Slugify an area name for its pack filename (spaces/slashes -> dashes)."""
    slug = _PACK_SLUG_SEP_RE.sub("-", name.strip().lower())
    slug = _PACK_SLUG_STRIP_RE.sub("", slug)
    slug = re.sub(r"-{2,}", "-", slug).strip("-")
    return slug or "area"


def _pack_as_list(value: object) -> list[str]:
    """Coerce an index field to a list of strings (unknown/missing -> [])."""
    if isinstance(value, str):
        return [value] if value.strip() else []
    if isinstance(value, list):
        return [str(item) for item in value if str(item).strip()]
    return []


def _pack_area(entry: dict) -> dict:
    """Normalise one raw index entry onto the canonical area shape."""
    name = str(entry.get("name") or "").strip() or "unnamed-area"
    folio = entry.get("folio")
    area: dict = {
        "name": name,
        "folio": str(folio).strip() if isinstance(folio, str) else "",
    }
    for key in _PACK_LIST_KEYS:
        area[key] = _pack_as_list(entry.get(key))
    return area


def _pack_from_subsystem(entry: dict) -> dict:
    """Map a manifest-snapshot subsystem entry onto the area shape."""
    mapped = dict(entry)
    if not mapped.get("binding_docs"):
        mapped["binding_docs"] = mapped.get("docs")
    if not mapped.get("source_roots"):
        mapped["source_roots"] = mapped.get("roots")
    return _pack_area(mapped)


def load_pack_index(path: Path) -> list[dict]:
    """Load a pack index from ``path``, accepting both supported forms.

    Detects the form by top-level key: ``{"areas": [...]}`` is the kit's own
    ``project.index.json``; ``{"subsystems": [...]}`` is a host manifest
    snapshot (``docs``/``roots`` map onto ``binding_docs``/``source_roots``).
    Unknown or missing per-entry keys become empty lists. Raises ``ValueError``
    when the document is neither form (a wrong file, not a quiet no-op).
    """
    data = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(data, dict) and isinstance(data.get("areas"), list):
        return [_pack_area(e) for e in data["areas"] if isinstance(e, dict)]
    if isinstance(data, dict) and isinstance(data.get("subsystems"), list):
        return [
            _pack_from_subsystem(e) for e in data["subsystems"] if isinstance(e, dict)
        ]
    msg = f"{path.name}: expected top-level 'areas' or 'subsystems' list"
    raise ValueError(msg)


def _pack_section(title: str, items: list[str]) -> list[str]:
    """Render one pack section as markdown lines (empty section -> no lines)."""
    if not items:
        return []
    return [f"## {title}", "", *(f"- {item}" for item in items), ""]


def _pack_body(root: Path, area: dict) -> str:
    """Compose one pack's full markdown text from a normalised area."""
    lines = [_PACK_MARKER, "", f"# {area['name']} — agent context pack", ""]
    lines += _pack_section("Folio", [area["folio"]] if area["folio"] else [])
    for key in _PACK_LIST_KEYS:
        items = area[key]
        if key == "source_roots":
            items = [
                entry if (root / entry).exists() else f"{entry} (MISSING)"
                for entry in items
            ]
        lines += _pack_section(_PACK_SECTION_TITLES[key], items)
    return "\n".join(lines).rstrip() + "\n"


def generate_packs(root: Path, config: Config, index: list[dict]) -> list[Path]:
    """Write one context pack per index area; return the written paths.

    Packs land in ``<root>/<state_dir>/contextpacks/<slug>.context.md``.
    ``source_roots`` entries are existence-checked against ``root`` and
    suffixed `` (MISSING)`` when absent, so a stale index is visible in the
    pack instead of silently misleading the agent reading it.
    """
    out_dir = root / config.state_dir / "contextpacks"
    written: list[Path] = []
    for entry in index:
        area = _pack_area(entry)
        path = out_dir / f"{_pack_slug(area['name'])}.context.md"
        atomic_write_text(path, _pack_body(root, area))
        written.append(path)
    return written


def pack_index_skeleton(project_name: str) -> str:
    """Return the planted ``project.index.json`` skeleton (JSON text).

    One example area with every field present-but-empty, plus a ``_comment``
    explaining how each field feeds the AgentContextPack generator
    (index-or-manifest input, design-spec 2.10).
    """
    skeleton = {
        "_comment": (
            "AgentContextPack index (design-spec 2.10). Each `areas` entry "
            "feeds one generated <state_dir>/contextpacks/<name>.context.md: "
            "`name` (the area; slugified into the pack filename), `folio` "
            "(the canonical entry-point doc for the area), `binding_docs` "
            "(authoritative contracts to read first), `source_roots` (key "
            "files/dirs; existence-checked at generation, missing ones "
            "flagged), `do_not_create` (existing systems an agent must not "
            "duplicate), `gates` (currently active expansion conditions), "
            "`verification` (commands to run before pushing). The generator "
            'also accepts a manifest snapshot ({"subsystems": [...]}) '
            "instead of this file."
        ),
        "project": project_name,
        "areas": [
            {
                "name": "example-area",
                "folio": "",
                "binding_docs": [],
                "source_roots": [],
                "do_not_create": [],
                "gates": [],
                "verification": [],
            },
        ],
    }
    return json.dumps(skeleton, indent=2) + "\n"
