repos:
  # Black - format
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude: ^(disbot/|minebot/|superbot-start/)

  # isort - import order
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: ^(disbot/|minebot/|superbot-start/)

  # Ruff - lint + autofix, fail commit if it had to fix anything
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.3
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        exclude: ^(disbot/|minebot/|superbot-start/)

  # Mypy - strict types
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-requests", "types-PyYAML"]
        exclude: ^(disbot/|minebot/|superbot-start/)

# Match PythonAnywhere
default_language_version:
  python: python3
