#!/usr/bin/env python3.10
"""Umbrella freshness reporter for every committed *generated* artifact (stdlib only, read-only).

The repo commits several files that are **produced by a generator** from the structured
sources — a dashboard payload, an env-var reference, the agent context packs. Each can
silently drift behind its generator when a source change ships but the artifact is never
re-exported. PR #1025 hit exactly this for one of them (``dashboard.json`` was missing
env-vars + a setting key that had shipped in #1020/#1023, and nothing reported it) and
added a single-artifact ``--drift`` reporter. This umbrella generalises that one report so
**no** committed generated file silently rots: it walks a small registry of
``(label, committed path(s), generator)`` and, per artifact, builds a fresh copy and
compares only the *structural identifier set* — never the volatile churn (timestamps,
build SHA, code line-numbers). A real surface drift (a shipped cog/command/env-var/setting
that was never re-exported) becomes a visible warning; an ordinary regeneration delta
(a moved line, a new timestamp) does not.

Registered artifacts:

* ``dashboard/data/dashboard.json`` — delegates to the existing
  ``check_dashboard_data.check_structural_drift`` (the working single-artifact prototype;
  reused, not duplicated).
* ``docs/operations/env-vars.md`` — the set of environment-variable **names** in the
  rendered table (code line-numbers, which shift constantly, are deliberately ignored).
* ``docs/agent/generated/*.context.md`` — the set of content lines per pack, with the
  volatile ``> Generated: <date>`` line dropped.

Run::

    python3.10 scripts/check_generated_artifacts_fresh.py          # warn-only (always exit 0)
    python3.10 scripts/check_generated_artifacts_fresh.py --strict # exit 1 if ANY artifact drifts
    python3.10 scripts/check_generated_artifacts_fresh.py --list   # show the registry, run nothing

**Warn-only by design.** The committed artifacts are regenerated by hand / on the
docs-reconciliation cadence, and many parallel sessions touch them, so drift is *expected*
between regenerations and must never gate per-push CI. ``--strict`` exists for an opt-in
cadence check (e.g. the reconciliation routine), not for the per-PR ``code-quality`` gate.

Reliability (Q-0105): **unverified** — this is a convenience guard, not load-bearing
runtime code. Confirm its verdicts against the live generators a few times across sessions
before trusting its green, and **delete this script if it proves unreliable** over multiple
sessions rather than working around it.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# sibling/tool loading (scripts/ and tools/ are not importable packages)
# ---------------------------------------------------------------------------
def _load_module(label: str, path: Path) -> ModuleType:
    """Load a standalone module file by path (the repo convention for scripts/tools)."""
    spec = importlib.util.spec_from_file_location(f"_fresh_{label}", path)
    if spec is None or spec.loader is None:  # pragma: no cover - import wiring
        raise ImportError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    # Register before exec so dataclasses in the loaded module can resolve their
    # ``__module__`` (the machinery reads it back out of ``sys.modules``).
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


# ---------------------------------------------------------------------------
# one drift finding
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class Drift:
    """One structural-drift warning for a registered artifact's surface."""

    artifact: str
    surface: str
    message: str


def _fmt_sample(items: set[Any], limit: int = 6) -> str:
    """Render a deterministic, truncated sample of identifiers for a message."""
    ordered = sorted(items, key=repr)
    shown = ", ".join(repr(i) for i in ordered[:limit])
    extra = len(ordered) - limit
    return f"{shown}{f' (+{extra} more)' if extra > 0 else ''}"


def _set_drift(
    artifact: str,
    surface: str,
    committed: set[Any],
    fresh: set[Any],
    refresh_hint: str,
) -> list[Drift]:
    """Compare two identifier sets and warn on either direction of drift.

    ``added`` = present in a fresh build but missing from the committed artifact
    (a source change that shipped but was never re-exported — the common case).
    ``removed`` = in the committed artifact but no longer produced (a stale entry).
    """
    findings: list[Drift] = []
    added = fresh - committed
    removed = committed - fresh
    if added:
        findings.append(
            Drift(
                artifact,
                surface,
                f"{len(added)} {surface} present in a fresh build but missing from "
                f"the committed artifact — {refresh_hint}: {_fmt_sample(added)}",
            ),
        )
    if removed:
        findings.append(
            Drift(
                artifact,
                surface,
                f"{len(removed)} {surface} in the committed artifact no longer produced "
                f"(stale) — {refresh_hint}: {_fmt_sample(removed)}",
            ),
        )
    return findings


# ---------------------------------------------------------------------------
# per-artifact drift checks (each returns warnings only; empty == fresh)
# ---------------------------------------------------------------------------
def drift_dashboard_json() -> list[Drift]:
    """Delegate to the existing dashboard structural-drift reporter (reuse, not duplicate)."""
    mod = _load_module("dashboard", REPO_ROOT / "scripts" / "check_dashboard_data.py")
    committed = json.loads(mod.DATA_FILE.read_text(encoding="utf-8"))
    fresh = mod._build_fresh()
    return [
        Drift("dashboard.json", "dashboard", issue.message)
        for issue in mod.check_structural_drift(committed, fresh)
    ]


# Structural identifier sets for the public site.json subset — only identity is
# compared (never order/volatile churn), mirroring the dashboard.json surfaces.
_SITE_SURFACES: dict[str, Callable[[dict[str, Any]], set[Any]]] = {
    "catalogue keys": lambda d: {e.get("key") for e in d.get("catalogue", [])},
    "command names": lambda d: {c.get("name") for c in d.get("commands", [])},
    "changelog dates": lambda d: {e.get("date") for e in d.get("bot_changelog", [])},
}


def drift_site_json() -> list[Drift]:
    """``botsite/data/site.json`` — the public subset (plan §5 / §2.2).

    Two kinds of finding (both surfaced here, so one report covers the artifact):

    * **whitelist** — the committed file's top-level keys must be a subset of the
      producer's ``SITE_TOPLEVEL_KEYS``; a stray key is the leak class (a non-public
      family reaching the marketing site) and is reported even though this umbrella
      is warn-only by default (``--strict`` turns it into an exit-1 cadence gate).
    * **structural freshness** — catalogue keys / command names / changelog dates
      present in a fresh subset but missing from the committed file (a source change
      that shipped but was never re-exported), and vice-versa. The volatile churn
      (build SHA, timestamps) is ignored, like the dashboard.json reporter.
    """
    mod = _load_module("dashboard", REPO_ROOT / "scripts" / "check_dashboard_data.py")
    site_path = mod.SITE_DATA_FILE
    if not site_path.exists():
        return [
            Drift(
                "site.json",
                "artifact",
                f"{site_path.relative_to(REPO_ROOT)} does not exist — re-run "
                f"scripts/export_dashboard_data.py",
            ),
        ]
    committed = json.loads(site_path.read_text(encoding="utf-8"))
    fresh = mod._export_module().build_site_subset(mod._build_fresh())

    findings: list[Drift] = []
    # whitelist (reuse the canonical assertion in check_dashboard_data)
    findings.extend(
        Drift("site.json", "whitelist", issue.message)
        for issue in mod.check_site_subset(committed, site_path=site_path)
    )
    # structural freshness
    for surface_name, surface in _SITE_SURFACES.items():
        findings.extend(
            _set_drift(
                "site.json",
                surface_name,
                surface(committed),
                surface(fresh),
                "re-run scripts/export_dashboard_data.py",
            ),
        )
    return findings


_ENV_VAR_ROW = re.compile(r"^\|\s*`([A-Z][A-Z0-9_]*)`", re.MULTILINE)


def _env_names(doc_text: str) -> set[str]:
    """The set of environment-variable names in a rendered env-vars.md table."""
    return set(_ENV_VAR_ROW.findall(doc_text))


def drift_env_vars_doc() -> list[Drift]:
    """``docs/operations/env-vars.md`` generated head vs a fresh ``scan_env_usage`` render.

    Compares only the env-var *name* set (the same regex applied to both the fresh
    render and the committed file, so there is no extraction asymmetry); the code
    ``file:line`` locations the doc also carries are volatile and intentionally ignored.
    Only the **generated head** (above ``END_MARKER``) is compared — the hand-maintained
    web-tier tail below it carries vars the scanner can't see, by design, so it must not
    register as drift (the #1119 footgun fix).
    """
    mod = _load_module("env", REPO_ROOT / "scripts" / "scan_env_usage.py")
    committed_path = REPO_ROOT / "docs" / "operations" / "env-vars.md"
    committed_head = committed_path.read_text(encoding="utf-8").split(
        mod.END_MARKER,
        1,
    )[0]
    fresh_doc = mod.render_doc(mod.scan_env_usage())
    return _set_drift(
        "env-vars.md",
        "env-var names",
        _env_names(committed_head),
        _env_names(fresh_doc),
        "re-run scripts/scan_env_usage.py --write-doc",
    )


_GENERATED_LINE = re.compile(r"^> Generated:\s", re.MULTILINE)


def _pack_lines(text: str) -> set[str]:
    """Stable content lines of a context pack — the volatile date line dropped."""
    return {
        line
        for line in text.splitlines()
        if line.strip() and not _GENERATED_LINE.match(line)
    }


def drift_context_packs() -> list[Drift]:
    """``docs/agent/generated/*.context.md`` vs a fresh ``build_pack`` render, per pack.

    Drops the ``> Generated: <date>`` line (the only intentionally volatile field) and
    compares the remaining content-line set, so a real index change that was never rebuilt
    shows up while a date-only delta does not (the #1025 structural-vs-volatile lesson).
    """
    mod = _load_module("packs", REPO_ROOT / "tools" / "agent_context" / "build_pack.py")
    out_dir = REPO_ROOT / "docs" / "agent" / "generated"
    subsystems: dict[str, Any] = mod._load_index()["subsystems"]
    findings: list[Drift] = []
    for name, sub in subsystems.items():
        fresh = _pack_lines(mod._render_pack(name, sub))
        committed_path = out_dir / f"{name}.context.md"
        committed = (
            _pack_lines(committed_path.read_text(encoding="utf-8"))
            if committed_path.exists()
            else set()
        )
        if not committed_path.exists():
            findings.append(
                Drift(
                    "context-packs",
                    name,
                    f"the index declares pack {name!r} but "
                    f"{committed_path.relative_to(REPO_ROOT)} does not exist — re-run "
                    f"tools/agent_context/build_pack.py",
                ),
            )
            continue
        findings.extend(
            _set_drift(
                "context-packs",
                f"{name} content lines",
                committed,
                fresh,
                "re-run tools/agent_context/build_pack.py",
            ),
        )
    return findings


# ---------------------------------------------------------------------------
# the registry
# ---------------------------------------------------------------------------
@dataclass(frozen=True)
class Artifact:
    """A committed generated artifact and the drift check that reports its freshness."""

    label: str
    committed: str
    generator: str
    check: Callable[[], list[Drift]]


REGISTRY: tuple[Artifact, ...] = (
    Artifact(
        "dashboard.json",
        "dashboard/data/dashboard.json",
        "scripts/export_dashboard_data.py",
        drift_dashboard_json,
    ),
    Artifact(
        "site.json",
        "botsite/data/site.json",
        "scripts/export_dashboard_data.py",
        drift_site_json,
    ),
    Artifact(
        "env-vars.md",
        "docs/operations/env-vars.md",
        "scripts/scan_env_usage.py --write-doc",
        drift_env_vars_doc,
    ),
    Artifact(
        "context-packs",
        "docs/agent/generated/*.context.md",
        "tools/agent_context/build_pack.py",
        drift_context_packs,
    ),
)


def check_all(registry: tuple[Artifact, ...] = REGISTRY) -> list[Drift]:
    """Run every registered artifact's drift check and return the combined warnings."""
    findings: list[Drift] = []
    for artifact in registry:
        findings.extend(artifact.check())
    return findings


def main(argv: list[str] | None = None) -> int:
    """CLI entry point. Warn-only by default; ``--strict`` exits 1 on any drift."""
    parser = argparse.ArgumentParser(
        description="Report structural drift for every committed generated artifact.",
    )
    parser.add_argument(
        "--strict",
        action="store_true",
        help="exit 1 if any artifact has drifted (opt-in; default is warn-only exit 0)",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="print the registry of committed generated artifacts and exit",
    )
    args = parser.parse_args(argv)

    if args.list:
        print("Committed generated artifacts (label — committed path ← generator):")
        for artifact in REGISTRY:
            print(f"  {artifact.label}: {artifact.committed} ← {artifact.generator}")
        return 0

    findings = check_all()
    for drift in findings:
        print(f"⚠ [{drift.artifact}] {drift.surface}: {drift.message}")

    if not findings:
        print(
            f"check_generated_artifacts_fresh: OK ✓ ({len(REGISTRY)} artifacts fresh)",
        )
        return 0

    print(
        f"\ncheck_generated_artifacts_fresh: {len(findings)} drift warning(s) across "
        f"{len({d.artifact for d in findings})} artifact(s)",
    )
    return 1 if args.strict else 0


if __name__ == "__main__":
    raise SystemExit(main())
