#!/usr/bin/env python3
"""Generate a one-glance feature-completion scoreboard from the completion ledger.

Parses the **completion ledger** tables in
``docs/planning/feature-completion/README.md`` and tallies how many S1 bot units sit
in each completion state — ``unassessed`` / ``assessed`` / ``certified`` — then injects
a summary block (headline: the *certified %*, the "done-done" number).

    python3.10 scripts/completion_scoreboard.py            # print the table
    python3.10 scripts/completion_scoreboard.py --write    # inject into the README
    python3.10 scripts/completion_scoreboard.py --check     # CI: fail if README is stale

This is the *feature-completeness* sibling of ``readiness_scoreboard.py`` (which scores
the orthogonal *risk/hardening* axis). The ledger is the source of truth; this is a
derived index.

Parse contract: only the **bare** state word in a ledger ``State`` cell is counted
(``unassessed`` / ``assessed`` / ``certified``). Cells that pair the word with a glyph
(e.g. ``▢ unassessed`` in the doc's explanatory tables) are deliberately *not* matched,
and the generated block between the markers is skipped — so the count is exactly the
ledger rows.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LEDGER = REPO_ROOT / "docs" / "planning" / "feature-completion" / "README.md"

START = "<!-- COMPLETION_SCOREBOARD:START (generated by scripts/completion_scoreboard.py) -->"
END = "<!-- COMPLETION_SCOREBOARD:END -->"

# Ordered worst → best so the rendered table reads as a progress ladder.
_STATES = ("unassessed", "assessed", "certified")
_GLYPH = {"unassessed": "▢", "assessed": "◐", "certified": "✔"}


@dataclass
class Tally:
    unassessed: int = 0
    assessed: int = 0
    certified: int = 0

    @property
    def total(self) -> int:
        return self.unassessed + self.assessed + self.certified

    def pct(self, count: int) -> int:
        return round(100 * count / self.total) if self.total else 0

    @property
    def count(self) -> dict[str, int]:
        return {
            "unassessed": self.unassessed,
            "assessed": self.assessed,
            "certified": self.certified,
        }


def _cell_state(cell: str) -> str | None:
    """Return the state iff ``cell`` is *exactly* a bare state word (bold or plain).

    Strips whitespace and ``*`` only — never glyphs — so a ``▢ unassessed`` cell in an
    explanatory table does not get counted as a ledger row.
    """
    s = cell.strip().strip("*").strip()
    return s if s in _STATES else None


def _strip_generated_block(text: str) -> str:
    """Remove the injected scoreboard block so its words are never re-tallied."""
    if START in text and END in text:
        return re.sub(
            re.escape(START) + r".*?" + re.escape(END),
            "",
            text,
            flags=re.DOTALL,
        )
    return text


def tally(text: str) -> Tally:
    t = Tally()
    for line in _strip_generated_block(text).splitlines():
        if not line.lstrip().startswith("|"):
            continue
        for cell in line.split("|"):
            state = _cell_state(cell)
            if state == "unassessed":
                t.unassessed += 1
            elif state == "assessed":
                t.assessed += 1
            elif state == "certified":
                t.certified += 1
    return t


def render(t: Tally) -> str:
    headline = (
        f"**{t.total} units · {t.certified} certified ({t.pct(t.certified)}%) · "
        f"{t.assessed} assessed · {t.unassessed} unassessed.**"
    )
    rows = [
        headline,
        "",
        "| Completion | Units | Share |",
        "|---|---:|---:|",
    ]
    for state in reversed(_STATES):  # certified → assessed → unassessed
        count = t.count[state]
        rows.append(f"| {_GLYPH[state]} {state} | {count} | {t.pct(count)}% |")
    rows.append(f"| **Total** | **{t.total}** | **100%** |")
    note = (
        "\n> _Generated by `scripts/completion_scoreboard.py` from the ledger tables "
        "below. **Certified %** is the headline “done-done” number — the share of S1 "
        "units the owner has signed off as feature-complete._"
    )
    return "\n".join(rows) + "\n" + note


def _inject(rendered: str) -> str:
    text = LEDGER.read_text(encoding="utf-8")
    block = f"{START}\n{rendered}\n{END}"
    if START in text and END in text:
        return re.sub(
            re.escape(START) + r".*?" + re.escape(END),
            block,
            text,
            flags=re.DOTALL,
        )
    raise SystemExit(
        "completion_scoreboard: markers not found in the ledger README — add "
        f"{START} / {END} where the scoreboard should render.",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Feature-completion scoreboard.")
    parser.add_argument("--write", action="store_true", help="Inject into the README.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the README block is stale.",
    )
    args = parser.parse_args(argv)

    rendered = render(tally(LEDGER.read_text(encoding="utf-8")))

    if args.check:
        current = LEDGER.read_text(encoding="utf-8")
        if _inject(rendered) != current:
            print(
                "completion_scoreboard: ledger scoreboard is stale — run --write.",
                file=sys.stderr,
            )
            return 1
        print("completion_scoreboard: ledger scoreboard up to date.")
        return 0

    if args.write:
        LEDGER.write_text(_inject(rendered), encoding="utf-8")
        print(
            f"completion_scoreboard: wrote scoreboard into "
            f"{LEDGER.relative_to(REPO_ROOT)}",
        )
        return 0

    print(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
