#!/usr/bin/env python3
"""Generate a one-glance production-readiness scoreboard from the readiness maps.

Parses the per-subsystem maps in ``docs/planning/production-readiness/`` and tallies
exact **Done / Partial / Not Done** status cells in their tables, per subsystem. The
result is a coarse "how production-ready is each slice?" signal that refreshes as a
hardening track lands and a map's rows flip.

    python3.10 scripts/readiness_scoreboard.py            # print the table
    python3.10 scripts/readiness_scoreboard.py --write    # inject into the README
    python3.10 scripts/readiness_scoreboard.py --check     # CI: fail if README is stale

Counts are **approximate by design** — only exact status cells in table rows are
tallied (headline cells like ``**Partial** — …`` are intentionally skipped). The maps
themselves are the source of truth; this is a derived index.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
MAPS_DIR = REPO_ROOT / "docs" / "planning" / "production-readiness"
README = MAPS_DIR / "README.md"

START = "<!-- SCOREBOARD:START (generated by scripts/readiness_scoreboard.py) -->"
END = "<!-- SCOREBOARD:END -->"

# map-file stem -> display name
_DISPLAY = {
    "ai-production-readiness-map-2026-06-12": "AI / Setup Advisor",
    "btd6-production-readiness-map-2026-06-12": "BTD6",
    "games-production-readiness-map-2026-06-12": "Games",
    "health-diagnostics-production-readiness-map-2026-06-12": "Health / diagnostics",
    "media-youtube-production-readiness-map-2026-06-12": "Media / YouTube",
    "server-management-production-readiness-map-2026-06-12": "Server management",
    "settings-bindings-provisioning-production-readiness-map-2026-06-12": "Settings / bindings / provisioning",
}

_STATUSES = ("Done", "Partial", "Not Done")


@dataclass
class Tally:
    done: int = 0
    partial: int = 0
    not_done: int = 0

    @property
    def total(self) -> int:
        return self.done + self.partial + self.not_done

    @property
    def pct(self) -> int:
        return round(100 * self.done / self.total) if self.total else 0


def _cell_status(cell: str) -> str | None:
    """Return the status if ``cell`` is exactly a status token (bold or plain)."""
    s = cell.strip().strip("*").strip()
    return s if s in _STATUSES else None


def tally_map(path: Path) -> Tally:
    t = Tally()
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.lstrip().startswith("|"):
            continue
        for cell in line.split("|"):
            status = _cell_status(cell)
            if status == "Done":
                t.done += 1
            elif status == "Partial":
                t.partial += 1
            elif status == "Not Done":
                t.not_done += 1
    return t


def collect() -> dict[str, Tally]:
    out: dict[str, Tally] = {}
    for path in sorted(MAPS_DIR.glob("*-production-readiness-map-*.md")):
        name = _DISPLAY.get(path.stem, path.stem)
        out[name] = tally_map(path)
    return out


def render(tallies: dict[str, Tally]) -> str:
    rows = [
        "| Subsystem | Done | Partial | Not Done | Done % | Map |",
        "|---|---:|---:|---:|---:|---|",
    ]
    agg = Tally()
    for name, t in sorted(tallies.items(), key=lambda kv: kv[1].pct):
        stem = next((s for s, d in _DISPLAY.items() if d == name), name)
        rows.append(
            f"| {name} | {t.done} | {t.partial} | {t.not_done} | {t.pct}% | "
            f"[map]({stem}.md) |",
        )
        agg.done += t.done
        agg.partial += t.partial
        agg.not_done += t.not_done
    rows.append(
        f"| **All subsystems** | **{agg.done}** | **{agg.partial}** | "
        f"**{agg.not_done}** | **{agg.pct}%** | — |",
    )
    note = (
        "\n> _Generated by `scripts/readiness_scoreboard.py` — approximate (exact status "
        "cells only). Every subsystem is **Partial**; see the "
        "[hardening roadmap](hardening-roadmap-2026-06-12.md) for the ranked backlog._"
    )
    return "\n".join(rows) + "\n" + note


def _inject(rendered: str) -> str:
    text = README.read_text(encoding="utf-8")
    block = f"{START}\n{rendered}\n{END}"
    if START in text and END in text:
        return re.sub(
            re.escape(START) + r".*?" + re.escape(END),
            block,
            text,
            flags=re.DOTALL,
        )
    # Append a new section if markers are absent.
    return text.rstrip() + "\n\n## Readiness scoreboard\n\n" + block + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Production-readiness scoreboard.")
    parser.add_argument(
        "--write",
        action="store_true",
        help="Inject the table into the README.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if the README block is stale.",
    )
    args = parser.parse_args(argv)

    rendered = render(collect())

    if args.check:
        current = README.read_text(encoding="utf-8")
        if _inject(rendered) != current:
            print(
                "readiness_scoreboard: README scoreboard is stale — run --write.",
                file=sys.stderr,
            )
            return 1
        print("readiness_scoreboard: README scoreboard up to date.")
        return 0

    if args.write:
        README.write_text(_inject(rendered), encoding="utf-8")
        print(
            f"readiness_scoreboard: wrote scoreboard into {README.relative_to(REPO_ROOT)}",
        )
        return 0

    print(rendered)
    return 0


if __name__ == "__main__":
    sys.exit(main())
