-- Migration 020: resource_validation_cache table (Phase 2a).
--
-- Stores the most recent validation status for guild resources
-- (channels, roles, categories, threads).  The discord.py guild object
-- remains the in-memory source of truth for resource content; this
-- table caches the validation status enum + timestamp so:
--
--   * Phase 4c diagnostics ("how many missing channels does this guild
--     have?") run as a single indexed query rather than re-resolving
--     every binding on each request.
--   * Phase 7.5 repair flows can enumerate auto-repairable resources
--     by status without re-probing every binding.
--   * Status survives bot restart — cogs do not lose validation state
--     just because the process restarted.
--
-- Schema:
--
--   guild_id            BIGINT          — discord guild id
--   kind                TEXT            — channel | role | category | thread
--   resource_id         BIGINT          — discord snowflake of the resource
--   status              TEXT            — bound | unresolved | missing | invalid
--   last_validated_at   TIMESTAMPTZ     — when the status was last computed
--   PRIMARY KEY (guild_id, kind, resource_id)
--
-- Bounded growth: row count is O(guild_resources × validations); the
-- cache is per-resource not per-binding, so a single mod-logs channel
-- referenced by 3 subsystems still occupies one row.
--
-- Forward-only; rollback is "drop the table" (no data is authoritative
-- here — content can be regenerated by a single validation sweep).

CREATE TABLE IF NOT EXISTS resource_validation_cache (
    guild_id           BIGINT       NOT NULL,
    kind               TEXT         NOT NULL,
    resource_id        BIGINT       NOT NULL,
    status             TEXT         NOT NULL,
    last_validated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    PRIMARY KEY (guild_id, kind, resource_id)
);

-- Status-filtered queries are the hot path for Phase 4c diagnostics.
CREATE INDEX IF NOT EXISTS idx_resource_validation_cache_status
    ON resource_validation_cache (guild_id, status);

-- Phase 4c also reads "resources validated > N hours ago" for refresh
-- scheduling.  Partial index keeps it small.
CREATE INDEX IF NOT EXISTS idx_resource_validation_cache_stale
    ON resource_validation_cache (last_validated_at)
    WHERE status IN ('unresolved', 'missing', 'invalid');
