"""Tests for the AgentContextPack generator (Lane B8).

Covers both accepted index forms (kit ``areas`` index and manifest
``subsystems`` snapshot), the NOT SOURCE OF TRUTH marker, existence-checked
source roots (the MISSING suffix), empty-section skipping, filename
slugification, and the planted ``project.index.json`` skeleton.
"""

import json
from pathlib import Path

import pytest

from engine.contextpack import generate_packs, load_pack_index, pack_index_skeleton
from engine.lib.config import Config

_MARKER = (
    "<!-- NOT SOURCE OF TRUTH — generated by substrate-kit; "
    "regenerate, do not edit. -->"
)


def _write_json(path: Path, data: dict) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# load_pack_index — both input forms
# ---------------------------------------------------------------------------


def test_load_kit_index_form(tmp_path):
    path = _write_json(
        tmp_path / "project.index.json",
        {
            "areas": [
                {
                    "name": "economy",
                    "folio": "docs/subsystems/economy.md",
                    "binding_docs": ["docs/architecture.md"],
                    "source_roots": ["src/economy"],
                    "do_not_create": ["a second wallet service"],
                    "gates": ["expansion gate 1"],
                    "verification": ["python3 -m pytest"],
                },
            ],
        },
    )
    areas = load_pack_index(path)
    assert len(areas) == 1
    area = areas[0]
    assert area["name"] == "economy"
    assert area["folio"] == "docs/subsystems/economy.md"
    assert area["binding_docs"] == ["docs/architecture.md"]
    assert area["source_roots"] == ["src/economy"]
    assert area["verification"] == ["python3 -m pytest"]


def test_load_manifest_snapshot_form_maps_docs_and_roots(tmp_path):
    path = _write_json(
        tmp_path / "manifest.json",
        {
            "subsystems": [
                {
                    "name": "ledger",
                    "docs": ["docs/ownership.md"],
                    "roots": ["src/ledger.py"],
                },
            ],
        },
    )
    areas = load_pack_index(path)
    assert len(areas) == 1
    area = areas[0]
    assert area["name"] == "ledger"
    assert area["binding_docs"] == ["docs/ownership.md"]
    assert area["source_roots"] == ["src/ledger.py"]
    # Unknown/missing keys become empty lists, folio an empty string.
    assert area["do_not_create"] == []
    assert area["gates"] == []
    assert area["verification"] == []
    assert area["folio"] == ""


def test_load_manifest_snapshot_accepts_source_roots_key(tmp_path):
    path = _write_json(
        tmp_path / "manifest.json",
        {"subsystems": [{"name": "core", "source_roots": ["src/core"]}]},
    )
    assert load_pack_index(path)[0]["source_roots"] == ["src/core"]


def test_load_unknown_form_raises(tmp_path):
    path = _write_json(tmp_path / "weird.json", {"things": []})
    with pytest.raises(ValueError, match="areas"):
        load_pack_index(path)


def test_skeleton_roundtrips_through_loader(tmp_path):
    path = tmp_path / "project.index.json"
    path.write_text(pack_index_skeleton("demo"), encoding="utf-8")
    areas = load_pack_index(path)
    assert len(areas) == 1
    assert areas[0]["name"] == "example-area"
    assert areas[0]["binding_docs"] == []


# ---------------------------------------------------------------------------
# generate_packs
# ---------------------------------------------------------------------------


def test_generated_pack_marker_heading_and_sections(tmp_path):
    (tmp_path / "src").mkdir()
    (tmp_path / "src" / "real.py").write_text("x = 1\n", encoding="utf-8")
    index = [
        {
            "name": "economy",
            "folio": "docs/subsystems/economy.md",
            "binding_docs": ["docs/architecture.md"],
            "source_roots": ["src/real.py", "src/gone.py"],
            "do_not_create": ["a second wallet"],
            "gates": ["gate 1"],
            "verification": ["python3 -m pytest"],
        },
    ]
    paths = generate_packs(tmp_path, Config(), index)
    assert len(paths) == 1
    path = paths[0]
    assert path == tmp_path / ".substrate" / "contextpacks" / "economy.context.md"
    text = path.read_text(encoding="utf-8")
    assert text.splitlines()[0] == _MARKER
    assert "# economy — agent context pack" in text
    assert "## Folio" in text
    assert "- docs/subsystems/economy.md" in text
    assert "## Binding docs" in text
    assert "## Source roots" in text
    assert "- src/real.py\n" in text
    assert "- src/real.py (MISSING)" not in text
    assert "- src/gone.py (MISSING)" in text
    assert "## Do-not-create" in text
    assert "## Gates" in text
    assert "## Verification" in text


def test_empty_sections_are_skipped(tmp_path):
    index = [{"name": "bare"}]
    (path,) = generate_packs(tmp_path, Config(), index)
    text = path.read_text(encoding="utf-8")
    assert "# bare — agent context pack" in text
    assert "##" not in text.replace("# bare", "")


def test_slugified_filenames(tmp_path):
    index = [{"name": "Data Store/Core"}, {"name": "  Weird   name  "}]
    paths = generate_packs(tmp_path, Config(), index)
    names = sorted(p.name for p in paths)
    assert names == ["data-store-core.context.md", "weird-name.context.md"]


def test_generate_respects_config_state_dir(tmp_path):
    config = Config(state_dir=".kitstate")
    (path,) = generate_packs(tmp_path, config, [{"name": "a"}])
    assert path.parent == tmp_path / ".kitstate" / "contextpacks"


# ---------------------------------------------------------------------------
# pack_index_skeleton
# ---------------------------------------------------------------------------


def test_skeleton_is_valid_json_with_comment_and_example_area():
    data = json.loads(pack_index_skeleton("demo-project"))
    assert data["project"] == "demo-project"
    assert "AgentContextPack" in data["_comment"]
    assert "subsystems" in data["_comment"]  # documents the manifest form too
    (area,) = data["areas"]
    assert area["name"] == "example-area"
    for key in ("binding_docs", "source_roots", "do_not_create", "gates"):
        assert area[key] == []
    assert area["verification"] == []
    assert area["folio"] == ""
